image:
  repository: demo-app
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

service:
  type: NodePort
  port: 5000
  nodePort: 30080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

replicaCount: 1
